### ISSUE TITLE
Cloud code: afterFind

### ISSUE THREAD

**Issue by jonas-db** [parse-server-modules/parse-evolution#1]
# Feature name
- Proposal: Cloud code: afterFind
- Authors: TBD
- Review Manager: TBD
- Status: **Awaiting review**
## Motivation

Assume that we want to know the amount of views of a blog post, so everytime a blog post is fetched with a GET request, the amount of views should be updated.
## Proposed solution

Introducing an afterFind cloud code function. This is similar to the existing triggers and provides a uniform way to have triggers for GET/POST/DELETE requests.
## Detailed design

Extending the cloud code with an afterFind function
## Alternatives considered

If i'm correct, there are two ways to solve this problem:

create a cloud function, which you call instead of querying a collection
after the fetch request, save the object again with the counter increased

While the first one is acceptable, the second is not. Although, I think that cloud code is meant for custom code, not for normal query requests. To remain consistent with the other cloud code, I propose the suggestion of afterFind.

**Comment by flovilmart** [comment]
Please use the template here: https://github.com/parse-server-modules/parse-evolution/blob/master/0000-template.md

and fill much of it, open a pull request by adding your new proposal in the proposals folder.
